
export const foodItems = [
    { category: "Burger", name: "Chicken Burger", price: 20, image: "src/chickenburger.png" },
    { category: "Burger", name: "Chicken Cheese Burger", price: 25, image: "src/chickenburger.png" },
    { category: "Burger", name: "Chicken Grilled Burger", price: 22, image: "src/chickenburger.png" },
    { category: "Burger", name: "Chicken Toasted Burger", price: 30, image: "src/chickenburger.png" },
    { category: "Burger", name: "Beef Burger", price: 19, image: "src/chickenburger.png" },
    { category: "Burger", name: "Beef Cheese Burger", price: 18, image: "src/chickenburger.png" },
    { category: "Burger", name: "Beef Grilled Burger", price: 20, image: "src/chickenburger.png" },
    { category: "Burger", name: "Beef Spicy Burger", price: 21, image: "src/chickenburger.png" },
    { category: "Burger", name: "Beef Toasted Burger", price: 24, image: "src/chickenburger.png" },
    { category: "Burger", name: "Egg Burger", price: 12, image: "src/chickenburger.png" },
    { category: "Burger", name: "Mayo Burger", price: 28, image: "src/chickenburger.png" },
    { category: "Burger", name: "Double Pattie Burger", price: 11, image: "src/chickenburger.png" },
    { category: "Burger", name: "Cheese Burger", price: 10, image: "src/chickenburger.png " },
    { category: "Pizza", name: "Chicken Pizza", price: 20, image: "src/pizza-content.jpg" },
    { category: "Pizza", name: "Chicken Pepparoni Pizza", price: 23, image: "src/pizza-content.jpg" },
    { category: "Pizza", name: "Chicken Fajita Pizza", price: 22, image: "src/pizza-content.jpg" },
    { category: "Pizza", name: "Chicken Mayo Pizza", price: 19, image: "src/pizza-content.jpg" },
    { category: "Pizza", name: "Chicken Garlic Pizza", price: 18, image: "src/pizza-content.jpg" },
    { category: "Pizza", name: "Mayo Garlic Pizza", price: 14, image: "src/pizza-content.jpg" },
    { category: "Pizza", name: "Double Cheese Pizza", price: 26, image: "src/pizza-content.jpg" },
    { category: "Pizza", name: "Koyla Kebab Pizza", price: 16, image: "src/pizza-content.jpg" },
    { category: "Pizza", name: "Chicken Cheese Pizza", price: 24, image: "src/pizza-content.jpg" },
    { category: "Pizza", name: "Cheese Pizza", price: 25, image: "src/pizza-content.jpg" },
    { category: "Biryani", name: "Chicken Biryani", price: 20, image: "src/birjani-content.png" },
    { category: "Biryani", name: "Mutton Biryani", price: 22, image: "src/birjani-content.png" },
    { category: "Biryani", name: "Beef Biryani", price: 25, image: "src/birjani-content.png" },
    { category: "Biryani", name: "Aalo Biryani", price: 18, image: "src/birjani-content.png" },
    { category: "Biryani", name: "Spicy Pulao", price: 23, image: "src/birjani-content.png" },
    { category: "Shawarma", name: "Chicken Shawarma", price: 10, image: "src/shawarma.jpeg" },
    { category: "Shawarma", name: "Double Pattie Shawarma", price: 15, image: "src/shawarma.jpeg" },
    { category: "Shawarma", name: "Beef Shawarma", price: 12, image: "src/shawarma.jpeg" },
  ];
  